"""empty message

Revision ID: 20a26edcad29
Revises: 728c7503d5ab
Create Date: 2019-01-05 07:14:11.683363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a26edcad29'
down_revision = '728c7503d5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('blacklisted_token', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('blacklisted_token')
    )
    op.drop_table('period')
    op.add_column('comments', sa.Column('created_on', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'is_approved')
    op.drop_column('comments', 'created_on')
    op.create_table('period',
    sa.Column('period_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_activity_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('activity_progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_on', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_activity_id'], ['activities.activity_id'], name='period_parent_activity_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('period_id', name='period_pkey')
    )
    op.drop_table('blacklisted')
    # ### end Alembic commands ###
